from workouts import cruise_interval_run
from workouts import fast_finish_run
from workouts import foundation_run
from workouts import hill_repetition_run
from workouts import long_interval_run
from workouts import long_run
from workouts import long_run_with_fast_finish
from workouts import long_run_with_speed_play
from workouts import marathon_simulator_run
from workouts import mixed_interval_run
from workouts import recovery_run
from workouts import short_interval_run
from workouts import speed_play_run
from workouts import tempo_run
from workouts import Workout

half_marathon: dict[int, dict[int, list[Workout | None]]] = {
    2: {
        1: [
            foundation_run[5],
            fast_finish_run[3],
            foundation_run[5],
            foundation_run[5],
            speed_play_run[4],
            foundation_run[5],
            long_run[2],
        ],
        2: [
            foundation_run[5],
            fast_finish_run[4],
            foundation_run[6],
            foundation_run[5],
            speed_play_run[5],
            foundation_run[5],
            long_run[2],
        ],
        3: [
            None,
            fast_finish_run[3],
            foundation_run[5],
            foundation_run[5],
            speed_play_run[4],
            foundation_run[5],
            long_run[1],
        ],
        4: [
            fast_finish_run[5],
            fast_finish_run[4],
            recovery_run[6],
            foundation_run[6],
            hill_repetition_run[5],
            recovery_run[5],
            long_run[5],
        ],
        5: [
            foundation_run[5],
            fast_finish_run[5],
            recovery_run[6],
            foundation_run[6],
            hill_repetition_run[6],
            recovery_run[6],
            long_run[7],
        ],
        6: [
            None,
            fast_finish_run[4],
            recovery_run[5],
            foundation_run[5],
            hill_repetition_run[4],
            recovery_run[5],
            long_run[3],
        ],
        7: [
            foundation_run[6],
            cruise_interval_run[1],
            recovery_run[6],
            foundation_run[6],
            short_interval_run[4],
            recovery_run[6],
            long_run_with_speed_play[1],
        ],
        8: [
            recovery_run[6],
            tempo_run[4],
            recovery_run[6],
            foundation_run[6],
            short_interval_run[5],
            recovery_run[6],
            long_run_with_speed_play[2],
        ],
        9: [
            None,
            cruise_interval_run[1],
            recovery_run[5],
            foundation_run[6],
            short_interval_run[3],
            recovery_run[5],
            long_run_with_fast_finish[1],
        ],
        10: [
            foundation_run[6],
            tempo_run[5],
            recovery_run[6],
            foundation_run[6],
            long_interval_run[3],
            recovery_run[6],
            long_run_with_speed_play[2],
        ],
        11: [
            recovery_run[6],
            cruise_interval_run[2],
            recovery_run[6],
            foundation_run[6],
            long_interval_run[6],
            recovery_run[6],
            long_run_with_fast_finish[2],
        ],
        12: [
            None,
            tempo_run[4],
            recovery_run[5],
            foundation_run[6],
            long_interval_run[3],
            recovery_run[5],
            long_run_with_speed_play[1],
        ],
        13: [
            foundation_run[6],
            tempo_run[7],
            recovery_run[6],
            foundation_run[6],
            mixed_interval_run[2],
            recovery_run[6],
            long_run_with_fast_finish[3],
        ],
        14: [
            recovery_run[5],
            tempo_run[5],
            recovery_run[5],
            foundation_run[4],
            mixed_interval_run[2],
            recovery_run[4],
            long_run_with_speed_play[1],
        ],
        15: [
            None,
            fast_finish_run[5],
            foundation_run[4],
            foundation_run[3],
            speed_play_run[2],
            recovery_run[2],
            None,
        ],
    }
}

marathon: dict[int, dict[int, list[Workout | None]]] = {
    1: {
        1: [
            None,
            fast_finish_run[2],
            foundation_run[3],
            foundation_run[3],
            speed_play_run[1],
            foundation_run[3],
            long_run[1],
        ],
        2: [
            None,
            fast_finish_run[3],
            foundation_run[4],
            foundation_run[3],
            speed_play_run[2],
            foundation_run[3],
            long_run[2],
        ],
        3: [
            None,
            fast_finish_run[2],
            foundation_run[3],
            foundation_run[3],
            speed_play_run[1],
            foundation_run[3],
            long_run[1],
        ],
        4: [
            None,
            fast_finish_run[4],
            foundation_run[4],
            foundation_run[3],
            hill_repetition_run[1],
            recovery_run[4],
            long_run[3],
        ],
        5: [
            None,
            fast_finish_run[6],
            foundation_run[4],
            foundation_run[4],
            hill_repetition_run[2],
            recovery_run[4],
            long_run[4],
        ],
        6: [
            None,
            fast_finish_run[4],
            foundation_run[3],
            foundation_run[4],
            hill_repetition_run[1],
            recovery_run[3],
            long_run[2],
        ],
        7: [
            None,
            fast_finish_run[7],
            foundation_run[5],
            foundation_run[4],
            hill_repetition_run[4],
            recovery_run[4],
            long_run[5],
        ],
        8: [
            None,
            fast_finish_run[8],
            foundation_run[5],
            foundation_run[5],
            hill_repetition_run[6],
            recovery_run[4],
            long_run[7],
        ],
        9: [
            None,
            fast_finish_run[6],
            foundation_run[4],
            foundation_run[4],
            hill_repetition_run[4],
            recovery_run[4],
            long_run[4],
        ],
        10: [
            None,
            tempo_run[2],
            recovery_run[5],
            foundation_run[5],
            short_interval_run[1],
            recovery_run[4],
            long_run[9],
        ],
        11: [
            None,
            cruise_interval_run[1],
            recovery_run[5],
            foundation_run[5],
            short_interval_run[2],
            recovery_run[5],
            long_run[11],
        ],
        12: [
            None,
            tempo_run[2],
            recovery_run[4],
            foundation_run[5],
            short_interval_run[1],
            recovery_run[4],
            long_run_with_speed_play[1],
        ],
        13: [
            None,
            tempo_run[3],
            recovery_run[5],
            foundation_run[6],
            long_interval_run[2],
            recovery_run[5],
            long_run_with_fast_finish[1],
        ],
        14: [
            None,
            tempo_run[4],
            recovery_run[6],
            foundation_run[6],
            long_interval_run[3],
            recovery_run[5],
            long_run_with_speed_play[2],
        ],
        15: [
            None,
            tempo_run[2],
            recovery_run[5],
            foundation_run[5],
            long_interval_run[1],
            recovery_run[5],
            marathon_simulator_run,
        ],
        16: [
            None,
            cruise_interval_run[2],
            recovery_run[6],
            foundation_run[6],
            mixed_interval_run[1],
            recovery_run[6],
            long_run_with_fast_finish[5],
        ],
        17: [
            None,
            tempo_run[4],
            foundation_run[5],
            foundation_run[5],
            mixed_interval_run[1],
            recovery_run[4],
            long_run_with_speed_play[2],
        ],
        18: [
            None,
            fast_finish_run[4],
            foundation_run[4],
            foundation_run[3],
            speed_play_run[2],
            recovery_run[1],
            None,
        ],
    }
}
